### ISSUE TITLE
DB Error 1044: Access denied

### ISSUE THREAD

**Issue by letenkov** [somsakc/docker-observium#1]
DB Error 1044: Access denied for user 'observium'@'%' to database 'observium'

**Comment by somsakc** [comment]
Hi,

I supposed that observium-mysql-init.sh script file was not copied to /home/docker/observium/mysql directory before you ran "docker-compose up" command in first time. Follow the following steps.

Run these commands to cleanup previous steps
$ cd /home/docker/observium  ### I guess you put all files here!
$ docker-compose rm          ### remove previos containers
$ sudo rm -fr db lock mysql  ### remove previous created database

Redeploy new containers 
$ cd /home/docker/observium
$ mkdir db lock mysql
$ cp observium-mysql-init.sh mysql/  ### I guess you missed this step
$ docker-compose up

Limitation: directory is fixed to /home/docker/observium directory because of docker-compose.yml file. 

Hope this help, thanks.
Somsak C.
