### ISSUE TITLE
Deployed in docker as per compose file.  Cannot auto discovery

### ISSUE THREAD

**Issue by thefunkygibbon** [somsakc/docker-observium#22]
i MUST be doing something wrong, but everytime i run  /opt/observium/discovery.php -h all  from the cli of the container it finishes within milliseconds and finds nothing.   I'm assuming that observium doesn't require sitting on the host network (else why would the compose but it in a bridged network??)

how can i go about getting all my hosts discovered please?

**Comment by somsakc** [comment]
a. Kindly see "Add Initial User and Device" for first time discovery for your devices. I am sure not you had followed these steps or not (sorry, if you followed it already).

https://docs.observium.org/install_debian/

b. if the problem is not solve. I thought you may double check your connection from observium to device whether reachable as well.
